application: multi-user
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: blog.app

- url: /css
  static_dir: css

libraries:
- name: jinja2
  version: latest

- name: PIL
  version: "1.1.7"